### PR TITLE
Major update

### LINKED ISSUE #17: JeaSessionConfiguration doesn't support [Ensure]::Absent
JeaSessionConfiguration can't be removed after it's added as setting [Ensure]::Absent doesn't do anything in the Set block.

### LINKED ISSUE #28: 'You cannot call a method on a null-valued expression' when using FunctionDefinitions
I have used the config from #25 and just added FunctionDefinitions.

``` PowerShell
Configuration Test1
{
    Import-DscResource -Module JeaDsc

    
    JeaRoleCapabilities TechnicianRoleCapability
    {
        Path = 'C:\Program Files\WindowsPowerShell\Modules\JeaDsc\RoleCapabilities\Technician.psrc'
        VisibleCmdlets = 'Get-WinEvent','Get-Service'
        FunctionDefinitions = "@{ Name = 'Test'; ScriptBlock = { Get-Date } }"
    }
}

Test1 -OutputPath d:\dsc
Start-DscConfiguration -Path d:\dsc -Wait -Verbose -Force
```

This results in the following error:

```
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]TechnicianRoleCapability] Checking file extension is psrc for: C:\Program Files\WindowsPowerShell\Modules\JeaDsc
\RoleCapabilities\Technician.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]TechnicianRoleCapability] Checking parent forlder is RoleCapabilities for: C:\Program Files\WindowsPowerShell\Mo
dules\JeaDsc\RoleCapabilities\Technician.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]TechnicianRoleCapability] Checking Folder is in PSModulePath is psrc for: C:\Program Files\WindowsPowerShell\Mod
ules\JeaDsc\RoleCapabilities\Technician.psrc
VERBOSE: [RAANDREE0]:                            [[JeaRoleCapabilities]TechnicianRoleCapability] Path is a valid psrc path. Returning true.
You cannot call a method on a null-valued expression.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : InvokeMethodOnNull,Compare-JeaConfiguration
    + PSComputerName        : localhost
 
VERBOSE: [RAANDREE0]: LCM:  [ End    Test     ]  [[JeaRoleCapabilities]TechnicianRoleCapability]  in 0.1290 seconds.
The PowerShell DSC resource '[JeaRoleCapabilities]TechnicianRoleCapability' with SourceInfo '::6::5::JeaRoleCapabilities' threw one or more non-terminating errors while running the 
Test functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [RAANDREE0]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.289 seconds
```

### LINKED ISSUE #33: JeaDsc: Converting to new CI pipeline
Work need to be done to convert this repository to use the new CI pipeline.

https://dsccommunity.org/blog/convert-a-module-for-continuous-delivery/

### PR DESCRIPTION
**Pull request by raandree**
This PR makes JeaDsc cover more scenarios and fixes

Fixes #33 
Fixes #28 
Fixes #17 

For this many parts of the resource have been rewritten. The current version of JeaDsc could not be used to create a JEA endpoint and a role capability has multiple multi-line functions in FunctionDefinitions like needed for 
https://github.com/dsccommunity/CommonTasks/blob/dev/CommonTasks/DscResources/DscDiagnostic/DscDiagnostic.schema.psm1.

Thanks to @iRon7 for the create function [ConvertTo-Expression](https://github.com/iRon7/ConvertTo-Expression) which saved a lot of time.

I was not be able to get the JeaRoleCapabilities.Tests.ps1 unit tests working with the Sampler. The JeaDsc module's psd1 file has to be imported using a fixed path which is impossible as the path contains the version. @gaelcolas, @johlju, maybe you have some ideas how to get them working.

@gaelcolas, @johlju, can you add the project to Azure Pipelines, please

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/jeadsc/34)

### CODE REVIEW

**Comment by johlju** [comment]
> The JeaDsc module's psd1 file has to be imported using a fixed path 

You should import `./output/JeaDsc` that will make `Import-Module` to find the module manifest regardless of module version.

**Comment by johlju** [comment]
Isn't is possible to use the `Initialize-TestEnvironment` the the resource type `'Class'´ to initialize this? I never tried to use class-based resources so I'm not much help here. I must dig into it to see how it could work if it does not work with was is available :)

**Comment by johlju** [comment]
I removed the AppVeyor project and setup Azure Pipelines for this repo.

**Comment by raandree** [comment]
@johlju, reproduced what the issue was with the unit test for the class

```
using module ..\..\output\JeaDsc\0.91.0\JeaDsc.psd1

**Comment by raandree** [comment]
Thanks, @johlju. I did not see the wood for the trees and was 100% sure that I have tried Import-Module already. However, it is more complex.

I have reproduced what the issue was with the unit test for the 'JeaRoleCapabilities' class. The mocking only works if the module is imported like this or with Import-Module but not after 'Initialize-TestEnvironment' was invoked.

I have tried to initialize the tests like in other modules but also then mocking does no longer work inside the class. It works outside of the class when being in the Pester tests. This is why I have removed them for now. As mocking is not needed to the integration test, these ones work as expected.

**Comment by raandree** [comment]
I have done these and some more changes. I need some help getting the code coverage working.

**Comment by johlju** [comment]
Waiting for @gaelcolas to add the correct variables to the Azure Pipelines project, after that we can merge this. @raandree are you ready for this PR to be merged?

**Comment by raandree** [comment]
@johlju, ready!

**Comment by raandree** [comment]
@johlju, can you have a look at https://github.com/dsccommunity/JeaDsc/runs/706943557, please? Build worked but the deployment did not.

**Comment by gaelcolas** [comment]
The API token does not have right to the package in the gallery because the owner is @ChrisLGardner not DSC Community.
I pinged Chris on slack so we can fix this :)

**Comment by johlju** [comment]
I have re-run the jobs now after DSC Community was made owner. New preview version is published.

**Comment by raandree** [comment]
@johlju, I just discovered a bug. Let's stay with the pre-release version for now. I should have some new later that week.

**Comment by johlju** [comment]
Cool! Tag me and I help review! 😊

**Comment by raandree** [comment]
Found the issue. JeaDsc comes with its own version of 'Test-DscParameterState' in 'JeaDsc.Common.psm1' but this one is overridden by the one in 'DscResource.Common.psm1'. Updatint 'DscResource.Common.psm1' is the next task then and in the meantime just changing the order how the both modules are loaded works around the issue.

**Comment by johlju** [comment]
I think we should rename the local one to something else in the meantime so they are not confused, e.g. `Test-JeaDscParameterState`.

**Comment by johlju** [comment]
Unless you have to to fix the issues in the DscResource.Common one faster. :)

**Pull request merged**
