### PR TITLE
Added Invoke-Build tasks

### PR DESCRIPTION
**Pull request by raandree**
#### Pull Request (PR) description
Added Invoke-Build tasks for publishing

#### Task list
- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/jeadsc/52)

### CODE REVIEW

**Review by johlju — APPROVED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/jeadsc/52)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @raandree)

**Review by johlju — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/jeadsc/52#-:-N1YQ4_Q263hCpOOzk4S:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @raandree)

**Comment by johlju** [comment]
I missed that. I saw the build failed but didn’t have time to look at why. Great that you sent in this too! 😃

**Comment by raandree** [comment]
@johlju, the token for the PowerShell gallery has been expired:

```
ERROR: Failed to publish module 'JeaDsc': 'nuget.exe failed to push Response status code does not indicate success: 403 (The specified API key is invalid, has expired, or does not have permission to access the specified package.).
'.
```

Can you update the token, please? I do not have access to the pipeline definition.

**Comment by johlju** [comment]
Me neither, please ping @gaelcolas on Slack. Gael is the only one with permission.

**Comment by gaelcolas** [comment]
I probably entered the wrong one a few weeks ago. Remind me in an hour or so :)

**Comment by johlju** [comment]
Reminder in an hour @gaelcolas 😃

**Comment by gaelcolas** [comment]
Done and successfully published. Thanks @johlju !

**Pull request merged**
