### PR TITLE
Removed unnecessary entries

### PR DESCRIPTION
**Pull request by raandree**
#### Pull Request (PR) description

In PowerShell 7, DSC resources published by this module cannot be found due to this bug: [Get-DscResource doesn't identify the class based DSC resource PowerShell/PSDesiredStateConfiguration#117](https://github.com/PowerShell/PSDesiredStateConfiguration/issues/117). This PR removes the unnecessary entries in the module manifest.

#### Task list

- [x] Added an entry to the change log under the Unreleased section of the file CHANGELOG.md.
      Entry should say what was changed and how that affects users (if applicable), and
      reference the issue being resolved (if applicable).
- [ ] Resource documentation added/updated in comment-based help.
- [ ] Resource parameter descriptions added/updated in comment-based help.
- [ ] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [ ] Integration tests added/updated (where possible). See [DSC Community Testing Guidelines](https://dsccommunity.org/guidelines/testing-guidelines).
- [x] New/changed code adheres to [DSC Community Style Guidelines](https://dsccommunity.org/styleguidelines).

- - -
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/JeaDsc/55)

### CODE REVIEW

**Review by johlju — CHANGES_REQUESTED** [review]
> Reviewed 1 of 3 files at r1, 3 of 3 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/JeaDsc/55)* status: all files reviewed, 4 unresolved discussions (waiting on @raandree)

___
*[`build.yaml` line 37 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6lLlG16NZys3f4Qzk:-NU6lLlG16NZys3f4Qzl:b8top8t) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/07010ec0229b0fc05b960dd1aa382d6d3c341654/build.yaml#L37)):*
> ```YAML
>     - Create_changelog_release_output
>     - Generate_Conceptual_Help
>     #- Generate_Wiki_Content
> ```

Why do we have to remove this task?



_Code quote:_
```YAML
#- Generate_Wiki_Content
```
___
*[`build.yaml` line 54 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6lHkYBQp5rHqf4N9h:-NU6lHkYBQp5rHqf4N9i:b8top8t) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/07010ec0229b0fc05b960dd1aa382d6d3c341654/build.yaml#L54)):*
> ```YAML
>     - publish_module_to_gallery
>     - Publish_Release_To_GitHub
>     #- Publish_GitHub_Wiki_Content
> ```

Why do we have to remove this task?



_Code quote:_
```YAML
#- Publish_GitHub_Wiki_Content
```
___
*[`build.yaml` line 67 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6k5714WTddrPl5JzH:-NU6k5714WTddrPl5JzI:b11emrw) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/76083026af9552ab9d5848846ef9b6d743665d40/build.yaml#L67)):*
> ```YAML
>     - Modules/DscResource.Common
>   Script:
>     - tests/Unit
> ```

We usually have just the unit tests here so that `./build.ps1 -Task test` does not make permanent changes to a contributors dev machine. Integration tests will run if this is just set to `tests`. We usually make a user opt-in to run them by running `./build.ps1 -Task test -PesterScript ./tests/Integration`. Are the integration tests in the repo such that they do not make changes to a contributors machine? 



_Code quote:_
```YAML
- tests/Unit
```
___
*[`source/JeaDsc.psd1` line 29 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6kz417nXRxSM3A5Oa:-NU6kz425oXfj_mGPhd4:bmhd7sm) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/76083026af9552ab9d5848846ef9b6d743665d40/source/JeaDsc.psd1#L29)):*
> ```PowerShell
>     VariablesToExport    = @()
> 
>     AliasesToExport      = @()
> ```

Do we need to remove `AliasesToExport` too? It would be good to have that one working as ModuleBuilder will generate that one automatically if there are aliases on on public commands.



_Code quote:_
```PowerShell
AliasesToExport      = @()
```

**Review by johlju — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/JeaDsc/55)* status: all files reviewed, 4 unresolved discussions (waiting on @raandree)

___
*[`source/JeaDsc.psd1` line 29 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6kz417nXRxSM3A5Oa:-NU6pQOp6PaFN6fsnkLi:b7dg6b0) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/76083026af9552ab9d5848846ef9b6d743665d40/source/JeaDsc.psd1#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Do we need to remove `AliasesToExport` too? It would be good to have that one working as ModuleBuilder will generate that one automatically if there are aliases on on public commands.
</blockquote></details>

In my tests (thanks to @raandree for steps to reproduce) I saw that it is enough to remove `CmdletsToExport`. I suggest just removing that property, and add a unit test e.g. `tests/QA/check_module_manifest.tests.ps1` and add the folder `tests/QA` as a folder to run for task `test`.

**Review by raandree — COMMENTED** [review]
Thanks, done all the changes

> *[Reviewable](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-:-NUBS4a96dyDgpG69l8b:b-47hy07)* status: 1 of 10 files reviewed, 4 unresolved discussions (waiting on @johlju)

___
*[`build.yaml` line 37 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6lLlG16NZys3f4Qzk:-NU6p28hCQrDku9Wm89S:byooczt) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/07010ec0229b0fc05b960dd1aa382d6d3c341654/build.yaml#L37)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we have to remove this task?
</blockquote></details>

Done, thanks for your last fix.
___
*[`build.yaml` line 54 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6lHkYBQp5rHqf4N9h:-NU6p3E_ANTDwOWO-Soc:byooczt) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/07010ec0229b0fc05b960dd1aa382d6d3c341654/build.yaml#L54)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

Why do we have to remove this task?
</blockquote></details>

Done, thanks for your last fix.
___
*[`build.yaml` line 67 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6k5714WTddrPl5JzH:-NU6rVIo8VXQ5oicwafC:b-kmpxji) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/76083026af9552ab9d5848846ef9b6d743665d40/build.yaml#L67)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

We usually have just the unit tests here so that `./build.ps1 -Task test` does not make permanent changes to a contributors dev machine. Integration tests will run if this is just set to `tests`. We usually make a user opt-in to run them by running `./build.ps1 -Task test -PesterScript ./tests/Integration`. Are the integration tests in the repo such that they do not make changes to a contributors machine? 
</blockquote></details>

I see, makes sense. Done.
___
*[`source/JeaDsc.psd1` line 29 at r2](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NU6kz417nXRxSM3A5Oa:-NU7GTZ94VZPmkNjvFwJ:b-896fix) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/76083026af9552ab9d5848846ef9b6d743665d40/source/JeaDsc.psd1#L29)):*
<details><summary><i>Previously, johlju (Johan Ljunggren) wrote…</i></summary><blockquote>

In my tests (thanks to @raandree for steps to reproduce) I saw that it is enough to remove `CmdletsToExport`. I suggest just removing that property, and add a unit test e.g. `tests/QA/check_module_manifest.tests.ps1` and add the folder `tests/QA` as a folder to run for task `test`.
</blockquote></details>

Done.

**Comment by raandree** [comment]
@johlju, do you think this is ready to be merged?

**Review by johlju — APPROVED** [review]
:lgtm:

> Reviewed 5 of 8 files at r3, 4 of 4 files at r4, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-:-NVVtmu-E7AjSM9DPAfU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @raandree)

___
*[`tests/QA/Module.Tests.ps1` line 8 at r4](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NVVtYsIEjcXs3uAfGnX:-NVVtYsJ6oB8_nTp1EQ7:b-y1sos5) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/d34f400fd76f7dd29563ff95bd116b56220a4cd0/tests/QA/Module.Tests.ps1#L8)):*
> ```PowerShell
> 
>     It "Does not contain key 'CmdletsToExport'" {
>         $psd1.ContainsKey('CmdletsToExport') | Should Be $false
> ```

We should use `Should -BeFalse`. But can be fixed in a new PR that converts the tests to Pester 5.
___
*[`tests/QA/Module.Tests.ps1` line 12 at r4](https://reviewable.io/reviews/dsccommunity/JeaDsc/55#-NVVtiHa7CHSHuXtLJaw:-NVVtiHa7CHSHuXtLJax:b4hk66i) ([raw file](https://github.com/dsccommunity/JeaDsc/blob/d34f400fd76f7dd29563ff95bd116b56220a4cd0/tests/QA/Module.Tests.ps1#L12)):*
> ```PowerShell
> 
>     It "Does contain key 'DscResourcesToExport'" {
>         $psd1.ContainsKey('DscResourcesToExport') | Should Be $true
> ```

We should use `Should -BeTrue`. But can be fixed in a new PR that converts the tests to Pester 5.

**Pull request merged**
