### PR TITLE
Moving the class based resources from nested modules to root module

### PR DESCRIPTION
**Pull request by NicolasBn**
#### Pull Request (PR) description

Added : 
- Adding herited classes that contains helper methods.
Based on this [discussion](https://github.com/gaelcolas/Sampler/pull/212#pullrequestreview-514656759).

Changed : 

- Moving the class based resources from nested modules to root module.
- Moving LocalizedData of class based resources in .strings.psd1 files.
Based on [stylesguidelines](https://dsccommunity.org/styleguidelines/localization/) of DscCommunity, and this [discussion](https://github.com/gaelcolas/Sampler/pull/212#pullrequestreview-516267912).

#### Task list

- [x] Added an entry under the Unreleased section of the change log in the CHANGELOG.md.
      Entry should say what was changed, and how that affects users (if applicable).
- [ ] Resource documentation added/updated in README.md in resource folder.
- [ ] Resource parameter descriptions added/updated in schema.mof
      and comment-based help.
- [ ] Comment-based help added/updated.
- [x] Localization strings added/updated in all localization files as appropriate.
- [ ] Examples appropriately added/updated.
- [ ] Unit tests added/updated. See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [ ] Integration tests added/updated (where possible). See [DSC Resource Testing Guidelines](https://github.com/PowerShell/DscResources/blob/master/TestsGuidelines.md).
- [x] New/changed code adheres to [DSC Resource Style Guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md) and [Best Practices](https://github.com/PowerShell/DscResources/blob/master/BestPractices.md).

---
This change is [Reviewable](https://reviewable.io/reviews/dsccommunity/jeadsc/45)

### CODE REVIEW

**Comment by raandree** [comment]
Thanks for the PR, @NicolasBn. Having a look at it right now and trying to fix the build errors.

**Comment by NicolasBn** [comment]
This [error](https://dev.azure.com/dsccommunity/JeaDsc/_build/results?buildId=3141&view=logs&j=47266b63-9d03-5281-d38b-75133a4264f6&t=4d8b314c-6b76-5ae4-aed5-2779b7a3afdb&l=109) is generated because JeaDsc.strings.psd1 has a `dummy` value and a compiled version of JeaDsc.psm1 is generated by ModuleBuilder. https://github.com/dsccommunity/JeaDsc/blob/e27250f5796e93d7ee93927d92c612684b2cdd6e/source/en-US/JeaDsc.strings.psd1#L2
**Proposition :** Remove dummy value in JeaDsc.strings.psd1

The pester test that generate this [error](https://dev.azure.com/dsccommunity/JeaDsc/_build/results?buildId=3141&view=logs&j=47266b63-9d03-5281-d38b-75133a4264f6&t=4d8b314c-6b76-5ae4-aed5-2779b7a3afdb&l=170) will be remove in next release version of [DscResource.Test](https://github.com/dsccommunity/DscResource.Test/pull/88).

**Comment by raandree** [comment]
Agreed. It would be perfect if we can remove the dummy files completely. 

I have seen your commit to [DscResource.Test](https://github.com/dsccommunity/DscResource.Test/commit/609b5f2e965e2bb761aadc4ec502c0674f9291a6). When will a new release with the fix be published?

The code looks good.

**Comment by NicolasBn** [comment]
> Agreed. It would be perfect if we can remove the dummy files completely.
> 
> The code looks good. I have just tested the code with a project I am using JeaDsc (https://github.com/raandree/FiJea) and the result with of the new version is as expected.
> 
> I have seen your commit to [DscResource.Test](https://github.com/dsccommunity/DscResource.Test/commit/609b5f2e965e2bb761aadc4ec502c0674f9291a6). When will a new release with the fix be published? As soon as there is a new version of DscResource.Test we can release also a new version of JeaDsc.

Non-regression code is good news !  

I removed the dummy object in my last commit. 

For the release version of DscResource.Test, that is not in my hand. 
Maybe @johlju or @gaelcolas can answer you.

**Comment by gaelcolas** [comment]
reopening to kick the build

**Comment by gaelcolas** [comment]
@raandree ready for you to review, merge and test. The pipeline passed.

**Review by raandree — APPROVED** [review]
LGTM

**Comment by raandree** [comment]
Thanks for the great work, @NicolasBn!

**Pull request merged**
